# debug, info, warning, error, fatal, panic
log_level = "debug"

master_proxy_addr = "127.0.0.1:1086"
http_retry = 3

scanner_pool_size = 10
scanner_max_retry = 2

probe_size = 32
probe_interval = 180
probe_timeout = 10

eviction_interval = 600
#evict failed state proxy added 30 minutes earlier
eviction_timeout = 1800

