# trace, debug, info, warning, error, fatal, panic
log_level = "trace"

master_proxy_addr = "127.0.0.1:1080"
http_retry = 3
http_timeout = 60

scanner_pool_size = 10
scanner_max_retry = 2

probe_size = 32
probe_interval = 180
probe_timeout = 10

eviction_interval = 600
#evict failed state proxy added 30 minutes earlier
eviction_timeout = 1800
#evict proxy with score lower than the specified value
eviction_score_threshold = 50.0

[Logging]
log_file_path = "roprox.log"

[DataSource]
user_agents = "https://developers.whatismybrowser.com/api/docs/latest/user-agent-database-dump-url-csv-sample.tar.gz"
user_agent_lifespan = 10

[Database]
host = "127.0.0.1"
port = 3306
schema = "db"
user_name = "mysql"
password = "password"
